name: Diy ADBRemoteATV APK CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Clone the repository
        run: |
          git clone https://github.com/SX-Code/ADBRemoteATV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build release with Gradle
        run: |
          cd ADBRemoteATV && chmod +x ./gradlew
          ./gradlew clean assembleRelease
          # ls -R ./ADBRemoteATV
          ls -R .
        # env:
        #   KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          # ./app/build/outputs/apk/release: ADB_Remote_ATV_20240627161101.apk
          # path: app/build/outputs/apk/release
          path: ADBRemoteATV/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

  # deploy:
  #   name: Deploy to GitHub Releases
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - name: Get the APK
  #       id: get_apk
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: app

  #     - name: Publish the APK to GitHub Releases
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         prerelease: true
  #         asset_name: sslpinning-demo.apk
  #         file: ${{ steps.get_apk.outputs.download-path }}/app-release.apk
  #         tag: ${{ github.ref }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
