name: Diy android-detector APK CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Clone the repository
        run: |
          git clone https://github.com/20000s/android-detector

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # set diy gradle version
      - name: Setup Gradle 6.7.1
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.7.1
      - name: Build with Gradle 8.5
        run: gradle build
      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v3
      #   with:
      #     gradle-home-cache-cleanup: true

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          add-to-path: true
          local-cache: true

      - name: Build with Gradle
        run: |
          cd android-detector/detector && chmod +x ./gradlew
          ./gradlew clean assembleRelease
          ls -R ./android-detector/detector/app
          # ls -R .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: APatch
          # path: app/build/outputs/apk/release
          path: android-detector/detector/app/build/outputs/apk/release
