name: Diy EasyTier Mobile IOS ipa CI

on:
  workflow_dispatch:
      
env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:

  build:
    name: Build iPhone ios ipa simulator
    # 环境
    runs-on: macos-latest
    steps:
      # Checkout 当前分支进行处理
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Clone the repository
        run: |
          git clone https://github.com/EasyTier/EasyTier
          cd EasyTier
      
      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # - name: Setup pnpm cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      - name: Install frontend dependencies
        run: |
          pwd
          ls
          cd EasyTier/easytier-gui
          pnpm -r install
          echo "\n\npnpm -r install succ"
          pnpm -r build
          echo "\n\npnpm -r build succ"

      # - name: Cargo cache
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.cargo
      #       ./target
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust target
        run: |
          # curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
          sh rustup.sh -y
          # bash ./.github/workflows/install_rust.sh
          echo "\n\nInstall rust succ"
          rustup target list
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim

          # rustup target add aarch64-linux-android
          # rustup target add armv7-linux-androideabi
          # rustup target add i686-linux-android
          # rustup target add x86_64-linux-android
      
      - name: Build IOS 
        run: |
          pwd
          ls
          cd EasyTier/easytier-gui
          # cd easytier-gui
          pnpm tauri ios init
          echo "\n\npnpm tauri ios init succ"
          # 执行交互式命令方法1，45为打印的 iphone 15 pro
          echo -e '45' | pnpm tauri ios dev
          # # 执行交互式命令方法2
          # sh ~/.github/workflows/tools/et_pnpm_ios_dev.sh
          ls -R . | grep -v 'node_modules|.vscode'
          # 在8行后面新插入两行行
          sed '9i\
              "iOS": { "developmentTeam": "v"},
              ' tauri.conf.json
          pnpm tauri ios build
          echo "\n\npnpm tauri ios build succ"
          ls -R ../ | grep -v 'node_modules|.vscode'
          ls -R . | grep -v 'node_modules|.vscode'


      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: easytier-gui-ipa
          path: |
            # EasyTier/*
            EasyTier/*/*.ipa
            # EasyTier/easytier-gui/src-tauri/gen/apple/build/arm64/*.ipa
