# This is a basic workflow to help you get started with Actions

name: Diy totk yz CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/totk-yz.yml'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      # pwd
      # D:/a/actions/actions/
      - name: Cloane the repository
        run: |
          # git clone --recursive https://git.dhcp.cc/root/pineapple-src
          # git clone --recursive https://git.silicon.moe/N-archive/pineapple-src
          curl -OJL https://o.dhcp.cc/yuzu-windows-msvc-source.zip
          7z x yuzu-windows-msvc-source.zip
          cd yuzu-windows-msvc-source
          git submodule update --init --recursive
          # git checkout EA-3591
          # git checkout EA-3621
          # git checkout EA-3932


      # https://github.com/microsoft/setup-msbuild/tree/v1.1.3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.1
      
      # https://github.com/marketplace/actions/install-vulkan-sdk
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          # version: 1.4.309.0
          version: latest
      
      - name: Build x86 and x64
        run: |
          cd yuzu-windows-msvc-source
          # 使用 MSVC 的简单命令行构建
          mkdir build
          cd build
          # cmake .. -G "Visual Studio 16 2019" -A x64
          cmake .. -DYUZU_USE_BUNDLED_VCPKG=ON -DYUZU_TESTS=OFF -DCMAKE_CXX_FLAGS="/arch:AVX2 /O3 /fp:fast /GL" -DCMAKE_C_FLAGS="/arch:AVX2 /O3 /fp:fast /GL" -DCMAKE_EXE_LINKER_FLAGS="/LTCG" -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release
          dir
          # ls -R .

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yz-my
          path: |
            yuzu-windows-msvc-source/build/bin
            # yuzu-windows-msvc-source/build/bin/Release
